// Тема 11. Урок 1.
int great10Count = 0;
int less10Count = 0;
int sum = 0;
int maxValue = int.MinValue;
int minValue = int.MaxValue;
Console.WriteLine("Введите первое целое число");
int num1 = int.Parse(Console.ReadLine());
sum += num1;
great10Count = num1 > 10 ? great10Count += 1 : great10Count;
less10Count = num1 < -10 ? less10Count += 1 : less10Count;
if (num1 > maxValue) maxValue = num1;
else if (num1 < minValue) minValue = num1;
Console.WriteLine("Введите второе целое число");
int num2 = int.Parse(Console.ReadLine());
sum += num2;
great10Count = (num2 > 10) ? great10Count += 1 : great10Count;
less10Count = (num2 < -10) ? less10Count += 1 : less10Count;
if (num2 > maxValue) maxValue = num2;
if (num2 < minValue) minValue = num2;
Console.WriteLine("Введите третье целое число");
int num3 = int.Parse(Console.ReadLine());
sum += num3;
great10Count = (num3 > 10) ? great10Count += 1 : great10Count;
less10Count = (num3 < -10) ? less10Count += 1 : less10Count;
if (num3 > maxValue) maxValue = num3;
if (num3 < minValue) minValue = num3;
Console.WriteLine("Введите четвертое целое число");
int num4 = int.Parse(Console.ReadLine());
sum += num4;
great10Count = (num4 > 10) ? great10Count += 1 : great10Count;
less10Count = (num4 < -10) ? less10Count += 1 : less10Count;
if (num4 > maxValue) maxValue = num4;
if (num4 < minValue) minValue = num4;
Console.WriteLine("Введите пятое целое число");
int num5 = int.Parse(Console.ReadLine());
sum += num5;
great10Count = (num5 > 10) ? great10Count += 1 : great10Count;
less10Count = (num5 < -10) ? less10Count += 1 : less10Count;
if (num5 > maxValue) maxValue = num5;
if (num5 < minValue) minValue = num5;
Console.WriteLine("Введите шестое целое число");
int num6 = int.Parse(Console.ReadLine());
sum += num6;
great10Count = (num6 > 10) ? great10Count += 1 : great10Count;
less10Count = (num6 < -10) ? less10Count += 1 : less10Count;
if (num6 > maxValue) maxValue = num6;
if (num6 < minValue) minValue = num6;
Console.WriteLine("Введите седьмое целое число");
int num7 = int.Parse(Console.ReadLine());
sum += num7;
great10Count = (num7 > 10) ? great10Count += 1 : great10Count;
less10Count = (num7 < -10) ? less10Count += 1 : less10Count;
if (num7 > maxValue) maxValue = num7;
if (num7 < minValue) minValue = num7;
Console.WriteLine("Введите восьмое целое число");
int num8 = int.Parse(Console.ReadLine());
sum += num8;
great10Count = (num8 > 10) ? great10Count += 1 : great10Count;
less10Count = (num8 < -10) ? less10Count += 1 : less10Count;
if (num8 > maxValue) maxValue = num8;
if (num8 < minValue) minValue = num8;
Console.WriteLine("Введите девятое целое число");
int num9 = int.Parse(Console.ReadLine());
sum += num9;
great10Count = (num9 > 10) ? great10Count += 1 : great10Count;
less10Count = (num9 < -10) ? less10Count += 1 : less10Count;
if (num9 > maxValue) maxValue = num9;
if (num9 < minValue) minValue = num9;
Console.WriteLine("Введите десятое целое число");
int num10 = int.Parse(Console.ReadLine());
sum += num10;
great10Count = (num10 > 10) ? great10Count += 1 : great10Count;
less10Count = (num10 < -10) ? less10Count += 1 : less10Count;
if (num10 > maxValue) maxValue = num10;
if (num10 < minValue) minValue = num10;
double avg = (double)sum / 10;
Console.WriteLine($"Сумма чисел: {sum}\n" +
    $"Количество числе больше 10: {great10Count}\n" +
    $"Количество чисел меньше -10: {less10Count}\n" +
    $"Среднее арифметическое: {avg}\n" +
    $"Максимальное значение: {maxValue}\n" +
    $"Минимальное значение: {minValue}");
